### ISSUE TITLE
How to access Wilson_* datasets?

### ISSUE THREAD

**Issue by patel-zeel** [hughsalimbeni/bayesian_benchmarks#20]
I am trying to access Wilson_* datasets but am not able to do so.

```py
from bayesian_benchmarks.data import Boston, Wilson_pol

data1 = Boston()
data2 = Wilson_pol()
```

`data1` loads correctly. `data2` throws the following error:

```
Traceback (most recent call last):
  File "/home/patel_zeel/CGLB-1/cglb_experiments/zdata.py", line 5, in <module>
    data2 = Wilson_pol()
  File "/home/patel_zeel/bayesian_benchmarks/bayesian_benchmarks/data.py", line 54, in __init__
    self.download()
  File "/home/patel_zeel/bayesian_benchmarks/bayesian_benchmarks/data.py", line 93, in download
    is_zipped = np.any([z in self.url for z in [".gz", ".zip", ".tar"]])
  File "/home/patel_zeel/bayesian_benchmarks/bayesian_benchmarks/data.py", line 93, in <listcomp>
    is_zipped = np.any([z in self.url for z in [".gz", ".zip", ".tar"]])
AttributeError: 'Wilson_pol' object has no attribute 'url'
```

**Comment by st--** [comment]
Hi @patel-zeel, the code points to this URL to download: https://drive.google.com/open?id=0BxWe_IuTnMFcYXhxdUNwRHBKTlU but it seems to no longer be publicly accessible... NB, I'm trying to maintain a running version of this package over here: https://github.com/secondmind-labs/bayesian_benchmarks

**Comment by patel-zeel** [comment]
Thanks a lot for the info, @st--.
